sonar.projectKey=devops-ecommerce-platform
sonar.projectName=DevOps E-Commerce Platform

sonar.sources=app
sonar.tests=tests

sonar.python.coverage.reportPaths=coverage.xml

sonar.sourceEncoding=UTF-8
